name: opam wix

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - windows-latest
        ocaml-compiler:
          - 4.14.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: install opam
        run: |
          echo $PATH
          opam repo add usual git+https://github.com/ocaml/opam-repository
          opam show seq --raw
          opam var root
          ls D:\.opam\repo\usual\packages\seq\seq.base\files\seq.install
          md5sum D:\.opam\&repo\usual\packages\seq\seq.base\files\seq.install
          opam install opam-devel.2.1.5 -vv
          ls _opam\bin
          cp _opam\bin\opam.exe D:\cygwin\bin
      - run: which opam

      - run: D:\cygwin\bin\curl.exe --help
      - run: D:\cygwin\bin\curl.exe -L -o wix311.zip https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
      - run: ls wix311.zip
      - name: Compile
        run: |
          opam install . --deps-only
          opam exec -- make build
      - name: Tests
        run: opam exec -- make test
      - run: opam config report
      - run: opam install .
      - run: opam wix --help

#          curl -L -o opam.tar.gz https://github.com/ocaml/opam/releases/download/2.1.5/opam-full-2.1.5.tar.gz
#          tar xvf opam.tar.gz
#          cd opam-full-2.1.5
#          opam exec -- make
#          opam exec -- make install
